/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as OnboardingSubjectsRouteImport } from './routes/onboarding/subjects'
import { Route as OnboardingSchoolRouteImport } from './routes/onboarding/school'
import { Route as OnboardingPlanRouteImport } from './routes/onboarding/plan'
import { Route as OnboardingLearningRouteImport } from './routes/onboarding/learning'
import { Route as OnboardingConfidenceRouteImport } from './routes/onboarding/confidence'
import { Route as OnboardingBoardRouteImport } from './routes/onboarding/board'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student-dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlannerOrderRouteImport } from './routes/_authenticated/planner-order'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedParentsRouteImport } from './routes/_authenticated/parents'
import { Route as AuthenticatedParentDashboardRouteImport } from './routes/_authenticated/parent-dashboard'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMcqsRouteImport } from './routes/_authenticated/mcqs'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedHomeworkRouteImport } from './routes/_authenticated/homework'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as DemoStudentRouteRouteImport } from './routes/demo/student/route'
import { Route as DemoParentRouteRouteImport } from './routes/demo/parent/route'
import { Route as DemoStudentVideosRouteImport } from './routes/demo/student/videos'
import { Route as DemoStudentPlannerRouteImport } from './routes/demo/student/planner'
import { Route as DemoStudentMessagesRouteImport } from './routes/demo/student/messages'
import { Route as DemoStudentMcqsRouteImport } from './routes/demo/student/mcqs'
import { Route as DemoStudentLiveRouteImport } from './routes/demo/student/live'
import { Route as DemoStudentHomeworkRouteImport } from './routes/demo/student/homework'
import { Route as DemoStudentDashboardRouteImport } from './routes/demo/student/dashboard'
import { Route as DemoStudentCurriculumRouteImport } from './routes/demo/student/curriculum'
import { Route as DemoParentDashboardRouteImport } from './routes/demo/parent/dashboard'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students_.$studentId'
import { Route as AuthenticatedMcqSetIdRouteImport } from './routes/_authenticated/mcq.$setId'
import { Route as AuthenticatedHomeworkHomeworkIdRouteImport } from './routes/_authenticated/homework_.$homeworkId'
import { Route as DemoStudentMcqSetIdRouteImport } from './routes/demo/student/mcq.$setId'
import { Route as DemoStudentHomeworkHomeworkIdRouteImport } from './routes/demo/student/homework_.$homeworkId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSubjectsRoute = OnboardingSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingSchoolRoute = OnboardingSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingPlanRoute = OnboardingPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingLearningRoute = OnboardingLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingConfidenceRoute = OnboardingConfidenceRouteImport.update({
  id: '/confidence',
  path: '/confidence',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingBoardRoute = OnboardingBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student-dashboard',
    path: '/student-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerOrderRoute =
  AuthenticatedPlannerOrderRouteImport.update({
    id: '/planner-order',
    path: '/planner-order',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentsRoute = AuthenticatedParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentDashboardRoute =
  AuthenticatedParentDashboardRouteImport.update({
    id: '/parent-dashboard',
    path: '/parent-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMcqsRoute = AuthenticatedMcqsRouteImport.update({
  id: '/mcqs',
  path: '/mcqs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeworkRoute = AuthenticatedHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DemoStudentRouteRoute = DemoStudentRouteRouteImport.update({
  id: '/demo/student',
  path: '/demo/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoParentRouteRoute = DemoParentRouteRouteImport.update({
  id: '/demo/parent',
  path: '/demo/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStudentVideosRoute = DemoStudentVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoStudentPlannerRoute = DemoStudentPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoStudentMessagesRoute = DemoStudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoStudentMcqsRoute = DemoStudentMcqsRouteImport.update({
  id: '/mcqs',
  path: '/mcqs',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoStudentLiveRoute = DemoStudentLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoStudentHomeworkRoute = DemoStudentHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoStudentDashboardRoute = DemoStudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoStudentCurriculumRoute = DemoStudentCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoParentDashboardRoute = DemoParentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoParentRouteRoute,
} as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students_/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMcqSetIdRoute = AuthenticatedMcqSetIdRouteImport.update({
  id: '/mcq/$setId',
  path: '/mcq/$setId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeworkHomeworkIdRoute =
  AuthenticatedHomeworkHomeworkIdRouteImport.update({
    id: '/homework_/$homeworkId',
    path: '/homework/$homeworkId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DemoStudentMcqSetIdRoute = DemoStudentMcqSetIdRouteImport.update({
  id: '/mcq/$setId',
  path: '/mcq/$setId',
  getParentRoute: () => DemoStudentRouteRoute,
} as any)
const DemoStudentHomeworkHomeworkIdRoute =
  DemoStudentHomeworkHomeworkIdRouteImport.update({
    id: '/homework_/$homeworkId',
    path: '/homework/$homeworkId',
    getParentRoute: () => DemoStudentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/our-story': typeof OurStoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/demo/parent': typeof DemoParentRouteRouteWithChildren
  '/demo/student': typeof DemoStudentRouteRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/homework': typeof AuthenticatedHomeworkRoute
  '/live': typeof AuthenticatedLiveRoute
  '/mcqs': typeof AuthenticatedMcqsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/parent-dashboard': typeof AuthenticatedParentDashboardRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/planner-order': typeof AuthenticatedPlannerOrderRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/student-dashboard': typeof AuthenticatedStudentDashboardRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/onboarding/board': typeof OnboardingBoardRoute
  '/onboarding/confidence': typeof OnboardingConfidenceRoute
  '/onboarding/learning': typeof OnboardingLearningRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/school': typeof OnboardingSchoolRoute
  '/onboarding/subjects': typeof OnboardingSubjectsRoute
  '/demo/': typeof DemoIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/homework/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/mcq/$setId': typeof AuthenticatedMcqSetIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/demo/parent/dashboard': typeof DemoParentDashboardRoute
  '/demo/student/curriculum': typeof DemoStudentCurriculumRoute
  '/demo/student/dashboard': typeof DemoStudentDashboardRoute
  '/demo/student/homework': typeof DemoStudentHomeworkRoute
  '/demo/student/live': typeof DemoStudentLiveRoute
  '/demo/student/mcqs': typeof DemoStudentMcqsRoute
  '/demo/student/messages': typeof DemoStudentMessagesRoute
  '/demo/student/planner': typeof DemoStudentPlannerRoute
  '/demo/student/videos': typeof DemoStudentVideosRoute
  '/demo/student/homework/$homeworkId': typeof DemoStudentHomeworkHomeworkIdRoute
  '/demo/student/mcq/$setId': typeof DemoStudentMcqSetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/our-story': typeof OurStoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/demo/parent': typeof DemoParentRouteRouteWithChildren
  '/demo/student': typeof DemoStudentRouteRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/homework': typeof AuthenticatedHomeworkRoute
  '/live': typeof AuthenticatedLiveRoute
  '/mcqs': typeof AuthenticatedMcqsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/parent-dashboard': typeof AuthenticatedParentDashboardRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/planner-order': typeof AuthenticatedPlannerOrderRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/student-dashboard': typeof AuthenticatedStudentDashboardRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/onboarding/board': typeof OnboardingBoardRoute
  '/onboarding/confidence': typeof OnboardingConfidenceRoute
  '/onboarding/learning': typeof OnboardingLearningRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/school': typeof OnboardingSchoolRoute
  '/onboarding/subjects': typeof OnboardingSubjectsRoute
  '/demo': typeof DemoIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/homework/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/mcq/$setId': typeof AuthenticatedMcqSetIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/demo/parent/dashboard': typeof DemoParentDashboardRoute
  '/demo/student/curriculum': typeof DemoStudentCurriculumRoute
  '/demo/student/dashboard': typeof DemoStudentDashboardRoute
  '/demo/student/homework': typeof DemoStudentHomeworkRoute
  '/demo/student/live': typeof DemoStudentLiveRoute
  '/demo/student/mcqs': typeof DemoStudentMcqsRoute
  '/demo/student/messages': typeof DemoStudentMessagesRoute
  '/demo/student/planner': typeof DemoStudentPlannerRoute
  '/demo/student/videos': typeof DemoStudentVideosRoute
  '/demo/student/homework/$homeworkId': typeof DemoStudentHomeworkHomeworkIdRoute
  '/demo/student/mcq/$setId': typeof DemoStudentMcqSetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/our-story': typeof OurStoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/demo/parent': typeof DemoParentRouteRouteWithChildren
  '/demo/student': typeof DemoStudentRouteRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/homework': typeof AuthenticatedHomeworkRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/mcqs': typeof AuthenticatedMcqsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/parent-dashboard': typeof AuthenticatedParentDashboardRoute
  '/_authenticated/parents': typeof AuthenticatedParentsRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/planner-order': typeof AuthenticatedPlannerOrderRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/student-dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/onboarding/board': typeof OnboardingBoardRoute
  '/onboarding/confidence': typeof OnboardingConfidenceRoute
  '/onboarding/learning': typeof OnboardingLearningRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/school': typeof OnboardingSchoolRoute
  '/onboarding/subjects': typeof OnboardingSubjectsRoute
  '/demo/': typeof DemoIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_authenticated/homework_/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/_authenticated/mcq/$setId': typeof AuthenticatedMcqSetIdRoute
  '/_authenticated/students_/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/demo/parent/dashboard': typeof DemoParentDashboardRoute
  '/demo/student/curriculum': typeof DemoStudentCurriculumRoute
  '/demo/student/dashboard': typeof DemoStudentDashboardRoute
  '/demo/student/homework': typeof DemoStudentHomeworkRoute
  '/demo/student/live': typeof DemoStudentLiveRoute
  '/demo/student/mcqs': typeof DemoStudentMcqsRoute
  '/demo/student/messages': typeof DemoStudentMessagesRoute
  '/demo/student/planner': typeof DemoStudentPlannerRoute
  '/demo/student/videos': typeof DemoStudentVideosRoute
  '/demo/student/homework_/$homeworkId': typeof DemoStudentHomeworkHomeworkIdRoute
  '/demo/student/mcq/$setId': typeof DemoStudentMcqSetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/auth'
    | '/how-it-works'
    | '/our-story'
    | '/reset-password'
    | '/demo/parent'
    | '/demo/student'
    | '/billing'
    | '/curriculum'
    | '/dashboard'
    | '/homework'
    | '/live'
    | '/mcqs'
    | '/messages'
    | '/notes'
    | '/parent-dashboard'
    | '/parents'
    | '/planner'
    | '/planner-order'
    | '/profile'
    | '/settings'
    | '/student-dashboard'
    | '/students'
    | '/tutor'
    | '/videos'
    | '/onboarding/board'
    | '/onboarding/confidence'
    | '/onboarding/learning'
    | '/onboarding/plan'
    | '/onboarding/school'
    | '/onboarding/subjects'
    | '/demo/'
    | '/onboarding/'
    | '/homework/$homeworkId'
    | '/mcq/$setId'
    | '/students/$studentId'
    | '/demo/parent/dashboard'
    | '/demo/student/curriculum'
    | '/demo/student/dashboard'
    | '/demo/student/homework'
    | '/demo/student/live'
    | '/demo/student/mcqs'
    | '/demo/student/messages'
    | '/demo/student/planner'
    | '/demo/student/videos'
    | '/demo/student/homework/$homeworkId'
    | '/demo/student/mcq/$setId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/our-story'
    | '/reset-password'
    | '/demo/parent'
    | '/demo/student'
    | '/billing'
    | '/curriculum'
    | '/dashboard'
    | '/homework'
    | '/live'
    | '/mcqs'
    | '/messages'
    | '/notes'
    | '/parent-dashboard'
    | '/parents'
    | '/planner'
    | '/planner-order'
    | '/profile'
    | '/settings'
    | '/student-dashboard'
    | '/students'
    | '/tutor'
    | '/videos'
    | '/onboarding/board'
    | '/onboarding/confidence'
    | '/onboarding/learning'
    | '/onboarding/plan'
    | '/onboarding/school'
    | '/onboarding/subjects'
    | '/demo'
    | '/onboarding'
    | '/homework/$homeworkId'
    | '/mcq/$setId'
    | '/students/$studentId'
    | '/demo/parent/dashboard'
    | '/demo/student/curriculum'
    | '/demo/student/dashboard'
    | '/demo/student/homework'
    | '/demo/student/live'
    | '/demo/student/mcqs'
    | '/demo/student/messages'
    | '/demo/student/planner'
    | '/demo/student/videos'
    | '/demo/student/homework/$homeworkId'
    | '/demo/student/mcq/$setId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/onboarding'
    | '/auth'
    | '/how-it-works'
    | '/our-story'
    | '/reset-password'
    | '/demo/parent'
    | '/demo/student'
    | '/_authenticated/billing'
    | '/_authenticated/curriculum'
    | '/_authenticated/dashboard'
    | '/_authenticated/homework'
    | '/_authenticated/live'
    | '/_authenticated/mcqs'
    | '/_authenticated/messages'
    | '/_authenticated/notes'
    | '/_authenticated/parent-dashboard'
    | '/_authenticated/parents'
    | '/_authenticated/planner'
    | '/_authenticated/planner-order'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/student-dashboard'
    | '/_authenticated/students'
    | '/_authenticated/tutor'
    | '/_authenticated/videos'
    | '/onboarding/board'
    | '/onboarding/confidence'
    | '/onboarding/learning'
    | '/onboarding/plan'
    | '/onboarding/school'
    | '/onboarding/subjects'
    | '/demo/'
    | '/onboarding/'
    | '/_authenticated/homework_/$homeworkId'
    | '/_authenticated/mcq/$setId'
    | '/_authenticated/students_/$studentId'
    | '/demo/parent/dashboard'
    | '/demo/student/curriculum'
    | '/demo/student/dashboard'
    | '/demo/student/homework'
    | '/demo/student/live'
    | '/demo/student/mcqs'
    | '/demo/student/messages'
    | '/demo/student/planner'
    | '/demo/student/videos'
    | '/demo/student/homework_/$homeworkId'
    | '/demo/student/mcq/$setId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OurStoryRoute: typeof OurStoryRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DemoParentRouteRoute: typeof DemoParentRouteRouteWithChildren
  DemoStudentRouteRoute: typeof DemoStudentRouteRouteWithChildren
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/subjects': {
      id: '/onboarding/subjects'
      path: '/subjects'
      fullPath: '/onboarding/subjects'
      preLoaderRoute: typeof OnboardingSubjectsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/school': {
      id: '/onboarding/school'
      path: '/school'
      fullPath: '/onboarding/school'
      preLoaderRoute: typeof OnboardingSchoolRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/plan': {
      id: '/onboarding/plan'
      path: '/plan'
      fullPath: '/onboarding/plan'
      preLoaderRoute: typeof OnboardingPlanRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/learning': {
      id: '/onboarding/learning'
      path: '/learning'
      fullPath: '/onboarding/learning'
      preLoaderRoute: typeof OnboardingLearningRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/confidence': {
      id: '/onboarding/confidence'
      path: '/confidence'
      fullPath: '/onboarding/confidence'
      preLoaderRoute: typeof OnboardingConfidenceRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/board': {
      id: '/onboarding/board'
      path: '/board'
      fullPath: '/onboarding/board'
      preLoaderRoute: typeof OnboardingBoardRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student-dashboard': {
      id: '/_authenticated/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner-order': {
      id: '/_authenticated/planner-order'
      path: '/planner-order'
      fullPath: '/planner-order'
      preLoaderRoute: typeof AuthenticatedPlannerOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent-dashboard': {
      id: '/_authenticated/parent-dashboard'
      path: '/parent-dashboard'
      fullPath: '/parent-dashboard'
      preLoaderRoute: typeof AuthenticatedParentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcqs': {
      id: '/_authenticated/mcqs'
      path: '/mcqs'
      fullPath: '/mcqs'
      preLoaderRoute: typeof AuthenticatedMcqsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homework': {
      id: '/_authenticated/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof AuthenticatedHomeworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/student': {
      id: '/demo/student'
      path: '/demo/student'
      fullPath: '/demo/student'
      preLoaderRoute: typeof DemoStudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/parent': {
      id: '/demo/parent'
      path: '/demo/parent'
      fullPath: '/demo/parent'
      preLoaderRoute: typeof DemoParentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/student/videos': {
      id: '/demo/student/videos'
      path: '/videos'
      fullPath: '/demo/student/videos'
      preLoaderRoute: typeof DemoStudentVideosRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/student/planner': {
      id: '/demo/student/planner'
      path: '/planner'
      fullPath: '/demo/student/planner'
      preLoaderRoute: typeof DemoStudentPlannerRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/student/messages': {
      id: '/demo/student/messages'
      path: '/messages'
      fullPath: '/demo/student/messages'
      preLoaderRoute: typeof DemoStudentMessagesRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/student/mcqs': {
      id: '/demo/student/mcqs'
      path: '/mcqs'
      fullPath: '/demo/student/mcqs'
      preLoaderRoute: typeof DemoStudentMcqsRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/student/live': {
      id: '/demo/student/live'
      path: '/live'
      fullPath: '/demo/student/live'
      preLoaderRoute: typeof DemoStudentLiveRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/student/homework': {
      id: '/demo/student/homework'
      path: '/homework'
      fullPath: '/demo/student/homework'
      preLoaderRoute: typeof DemoStudentHomeworkRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/student/dashboard': {
      id: '/demo/student/dashboard'
      path: '/dashboard'
      fullPath: '/demo/student/dashboard'
      preLoaderRoute: typeof DemoStudentDashboardRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/student/curriculum': {
      id: '/demo/student/curriculum'
      path: '/curriculum'
      fullPath: '/demo/student/curriculum'
      preLoaderRoute: typeof DemoStudentCurriculumRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/parent/dashboard': {
      id: '/demo/parent/dashboard'
      path: '/dashboard'
      fullPath: '/demo/parent/dashboard'
      preLoaderRoute: typeof DemoParentDashboardRouteImport
      parentRoute: typeof DemoParentRouteRoute
    }
    '/_authenticated/students_/$studentId': {
      id: '/_authenticated/students_/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcq/$setId': {
      id: '/_authenticated/mcq/$setId'
      path: '/mcq/$setId'
      fullPath: '/mcq/$setId'
      preLoaderRoute: typeof AuthenticatedMcqSetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homework_/$homeworkId': {
      id: '/_authenticated/homework_/$homeworkId'
      path: '/homework/$homeworkId'
      fullPath: '/homework/$homeworkId'
      preLoaderRoute: typeof AuthenticatedHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/student/mcq/$setId': {
      id: '/demo/student/mcq/$setId'
      path: '/mcq/$setId'
      fullPath: '/demo/student/mcq/$setId'
      preLoaderRoute: typeof DemoStudentMcqSetIdRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
    '/demo/student/homework_/$homeworkId': {
      id: '/demo/student/homework_/$homeworkId'
      path: '/homework/$homeworkId'
      fullPath: '/demo/student/homework/$homeworkId'
      preLoaderRoute: typeof DemoStudentHomeworkHomeworkIdRouteImport
      parentRoute: typeof DemoStudentRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeworkRoute: typeof AuthenticatedHomeworkRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMcqsRoute: typeof AuthenticatedMcqsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedParentDashboardRoute: typeof AuthenticatedParentDashboardRoute
  AuthenticatedParentsRoute: typeof AuthenticatedParentsRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPlannerOrderRoute: typeof AuthenticatedPlannerOrderRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedHomeworkHomeworkIdRoute: typeof AuthenticatedHomeworkHomeworkIdRoute
  AuthenticatedMcqSetIdRoute: typeof AuthenticatedMcqSetIdRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeworkRoute: AuthenticatedHomeworkRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMcqsRoute: AuthenticatedMcqsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedParentDashboardRoute: AuthenticatedParentDashboardRoute,
  AuthenticatedParentsRoute: AuthenticatedParentsRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPlannerOrderRoute: AuthenticatedPlannerOrderRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedHomeworkHomeworkIdRoute: AuthenticatedHomeworkHomeworkIdRoute,
  AuthenticatedMcqSetIdRoute: AuthenticatedMcqSetIdRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OnboardingRouteRouteChildren {
  OnboardingBoardRoute: typeof OnboardingBoardRoute
  OnboardingConfidenceRoute: typeof OnboardingConfidenceRoute
  OnboardingLearningRoute: typeof OnboardingLearningRoute
  OnboardingPlanRoute: typeof OnboardingPlanRoute
  OnboardingSchoolRoute: typeof OnboardingSchoolRoute
  OnboardingSubjectsRoute: typeof OnboardingSubjectsRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingBoardRoute: OnboardingBoardRoute,
  OnboardingConfidenceRoute: OnboardingConfidenceRoute,
  OnboardingLearningRoute: OnboardingLearningRoute,
  OnboardingPlanRoute: OnboardingPlanRoute,
  OnboardingSchoolRoute: OnboardingSchoolRoute,
  OnboardingSubjectsRoute: OnboardingSubjectsRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface DemoParentRouteRouteChildren {
  DemoParentDashboardRoute: typeof DemoParentDashboardRoute
}

const DemoParentRouteRouteChildren: DemoParentRouteRouteChildren = {
  DemoParentDashboardRoute: DemoParentDashboardRoute,
}

const DemoParentRouteRouteWithChildren = DemoParentRouteRoute._addFileChildren(
  DemoParentRouteRouteChildren,
)

interface DemoStudentRouteRouteChildren {
  DemoStudentCurriculumRoute: typeof DemoStudentCurriculumRoute
  DemoStudentDashboardRoute: typeof DemoStudentDashboardRoute
  DemoStudentHomeworkRoute: typeof DemoStudentHomeworkRoute
  DemoStudentLiveRoute: typeof DemoStudentLiveRoute
  DemoStudentMcqsRoute: typeof DemoStudentMcqsRoute
  DemoStudentMessagesRoute: typeof DemoStudentMessagesRoute
  DemoStudentPlannerRoute: typeof DemoStudentPlannerRoute
  DemoStudentVideosRoute: typeof DemoStudentVideosRoute
  DemoStudentHomeworkHomeworkIdRoute: typeof DemoStudentHomeworkHomeworkIdRoute
  DemoStudentMcqSetIdRoute: typeof DemoStudentMcqSetIdRoute
}

const DemoStudentRouteRouteChildren: DemoStudentRouteRouteChildren = {
  DemoStudentCurriculumRoute: DemoStudentCurriculumRoute,
  DemoStudentDashboardRoute: DemoStudentDashboardRoute,
  DemoStudentHomeworkRoute: DemoStudentHomeworkRoute,
  DemoStudentLiveRoute: DemoStudentLiveRoute,
  DemoStudentMcqsRoute: DemoStudentMcqsRoute,
  DemoStudentMessagesRoute: DemoStudentMessagesRoute,
  DemoStudentPlannerRoute: DemoStudentPlannerRoute,
  DemoStudentVideosRoute: DemoStudentVideosRoute,
  DemoStudentHomeworkHomeworkIdRoute: DemoStudentHomeworkHomeworkIdRoute,
  DemoStudentMcqSetIdRoute: DemoStudentMcqSetIdRoute,
}

const DemoStudentRouteRouteWithChildren =
  DemoStudentRouteRoute._addFileChildren(DemoStudentRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  OurStoryRoute: OurStoryRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DemoParentRouteRoute: DemoParentRouteRouteWithChildren,
  DemoStudentRouteRoute: DemoStudentRouteRouteWithChildren,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
