-- S-18: deleting a topic or quiz set no longer destroys students' work.
--
-- Foreign keys cascade topics -> spec_points -> mcq_sets -> mcq_attempts, and
-- spec_points -> the planner's per-student tables. So a tutor deleting a topic
-- or a quiz silently deleted every student's attempts, scores, confidence
-- ratings, review history and plan for it, and the confirmation said nothing
-- about student data.
--
-- Ali's decision (1 Oct 2026): block the delete, and say how much student data
-- is in the way. A topic, spec point or quiz no student has touched still
-- deletes as before. The guards are triggers, so every route is covered: the
-- curriculum page, the quiz manager and the REST API alike. On a topic they
-- run before the cascade, so the topic's own message is the one shown.
--
-- And since a bad quiz could only be regenerated by deleting it first,
-- replace_generated_mcq_questions swaps a shared quiz's questions in place,
-- under the same set id. Attempts keep the score, total and per-point results
-- grade_mcq_attempt froze when they were taken.

-- Students with work or planner history on these spec points (or this topic),
-- and quiz attempts on them. Security definer: the count must see every
-- student's rows, whoever is deleting.
create or replace function private.student_data_on_points(_point_ids uuid[], _topic_id uuid default null)
 returns table(students int, attempts int)
 language sql
 stable
 security definer
 set search_path to ''
as $function$
  with taken as (
    select a.user_id
    from public.mcq_attempts a
    join public.mcq_sets s on s.id = a.set_id
    where s.spec_point_id = any(_point_ids)
  ),
  touched as (
    select user_id as student_id from taken
    union select student_id from public.student_spec_point_confidence where spec_point_id = any(_point_ids)
    union select student_id from public.student_spec_point_schedule where spec_point_id = any(_point_ids)
    union select student_id from public.student_spec_point_reviews where spec_point_id = any(_point_ids)
    union select student_id from public.student_plan_overrides where spec_point_id = any(_point_ids)
    union select p.student_id
          from public.student_weekly_plan_points pp
          join public.student_weekly_plans p on p.id = pp.plan_id
          where pp.spec_point_id = any(_point_ids)
    union select student_id from public.student_topic_confidence where topic_id = _topic_id
  )
  select (select count(distinct student_id)::int from touched),
         (select count(*)::int from taken);
$function$;

revoke all on function private.student_data_on_points(uuid[], uuid) from public, anon, authenticated;

create or replace function private.refuse_deleting_student_data()
 returns trigger
 language plpgsql
 security definer
 set search_path to ''
as $function$
declare
  _students int;
  _attempts int;
  _what text;
  _people text;
begin
  if tg_table_name = 'mcq_sets' then
    select count(distinct a.user_id)::int, count(*)::int
      into _students, _attempts
    from public.mcq_attempts a
    where a.set_id = old.id;
    if _attempts = 0 then
      return old;
    end if;
    raise exception using
      errcode = 'P0001',
      message = format(
        'Students have taken this quiz (%s %s by %s %s), so it can''t be deleted: their results would go with it. To fix its questions, use "Replace questions" on its spec point.',
        _attempts, case when _attempts = 1 then 'attempt' else 'attempts' end,
        _students, case when _students = 1 then 'student' else 'students' end);
  end if;

  if tg_table_name = 'topics' then
    select d.students, d.attempts into _students, _attempts
    from private.student_data_on_points(
      array(select sp.id from public.spec_points sp where sp.topic_id = old.id), old.id) d;
    _what := 'topic';
  else
    select d.students, d.attempts into _students, _attempts
    from private.student_data_on_points(array[old.id]) d;
    _what := 'spec point';
  end if;

  if _students = 0 and _attempts = 0 then
    return old;
  end if;
  _people := format('%s %s', _students, case when _students = 1 then 'student has' else 'students have' end);
  raise exception using
    errcode = 'P0001',
    message = format(
      'This %s can''t be deleted: %s work or planner history on it%s. Deleting it would erase that for good.',
      _what, _people,
      case when _attempts > 0
        then format(' (%s quiz %s)', _attempts, case when _attempts = 1 then 'attempt' else 'attempts' end)
        else '' end);
end;
$function$;

revoke all on function private.refuse_deleting_student_data() from public, anon, authenticated;

drop trigger if exists t_topics_keep_student_data on public.topics;
create trigger t_topics_keep_student_data
  before delete on public.topics
  for each row execute function private.refuse_deleting_student_data();

drop trigger if exists t_spec_points_keep_student_data on public.spec_points;
create trigger t_spec_points_keep_student_data
  before delete on public.spec_points
  for each row execute function private.refuse_deleting_student_data();

drop trigger if exists t_mcq_sets_keep_student_data on public.mcq_sets;
create trigger t_mcq_sets_keep_student_data
  before delete on public.mcq_sets
  for each row execute function private.refuse_deleting_student_data();

-- A shared quiz's questions, replaced in place. Called by the app server with
-- its own credential after it has checked the caller is a tutor, as
-- ensure_generated_mcq_set is. The same checks as that function apply to the
-- new questions.
create or replace function public.replace_generated_mcq_questions(_set_id uuid, _questions jsonb)
 returns integer
 language plpgsql
 security definer
 set search_path to ''
as $function$
declare
  _point uuid;
  _count int;
begin
  -- Locks the set, so two replacements run one after the other.
  select s.spec_point_id into _point
  from public.mcq_sets s
  where s.id = _set_id and s.origin = 'generated'
  for update;
  if _point is null then
    raise exception 'Quiz not found';
  end if;

  if jsonb_typeof(_questions) is distinct from 'array' or jsonb_array_length(_questions) = 0 then
    raise exception 'Refusing to replace a quiz with no questions';
  end if;

  if exists (
    select 1 from jsonb_array_elements(_questions) q
    where nullif(btrim(coalesce(q ->> 'question', '')), '') is null
       or jsonb_typeof(q -> 'options') is distinct from 'array'
       or jsonb_array_length(q -> 'options') <> 4
       or jsonb_typeof(q -> 'correct_index') is distinct from 'number'
       or (q ->> 'correct_index')::numeric not in (0, 1, 2, 3)
  ) then
    raise exception 'A question is missing its text, four options or a valid answer';
  end if;

  delete from public.mcq_questions where set_id = _set_id;

  insert into public.mcq_questions
    (set_id, position, question, options, correct_index, explanation, spec_point_id)
  select
    _set_id,
    (t.ord - 1)::int,
    btrim(t.q ->> 'question'),
    t.q -> 'options',
    (t.q ->> 'correct_index')::int,
    nullif(btrim(coalesce(t.q ->> 'explanation', '')), ''),
    _point
  from jsonb_array_elements(_questions) with ordinality as t(q, ord);
  get diagnostics _count = row_count;

  update public.mcq_sets set updated_at = now() where id = _set_id;
  return _count;
end;
$function$;

revoke all on function public.replace_generated_mcq_questions(uuid, jsonb) from public, anon, authenticated;
grant execute on function public.replace_generated_mcq_questions(uuid, jsonb) to service_role;
